Add CircleCI build
* Add build and publish jobs.
* Add style check to Makefile.
* Setup Go modules.
* Add binary to .gitignore.

diff --git a/stuff/Makefile b/stuff/Makefile
--- a/stuff/Makefile
+++ b/stuff/Makefile
@@ -2,6 +2,9 @@
 # features of 'make'
 ##
 
+GO        ?= go
+GOFMT     ?= $(GO)fmt
+
 all : stuff test
 
 stuff: *.go
@@ -12,3 +15,12 @@ test:
 
 clean:
 	rm -f stuff
+
+style:
+	@echo ">> checking code style"
+	@fmtRes=$$($(GOFMT) -d $$(find . -path ./vendor -prune -o -name '*.go' -print)); \
+	if [ -n "$${fmtRes}" ]; then \
+		echo "gofmt checking failed!"; echo "$${fmtRes}"; echo; \
+		echo "Please ensure you are using $$($(GO) version) for formatting code."; \
+		exit 1; \
+	fi
